# Both supported build entrypoints must compile the same production implementations.
get_filename_component(SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
file(READ "${SOURCE_ROOT}/CMakeLists.txt" CMAKE_SOURCE)
file(READ "${SOURCE_ROOT}/vs/FastFile.vcxproj" VS_SOURCE)
string(REGEX MATCHALL "src/[A-Za-z0-9_.]+[.]cpp" CPP_SOURCES "${CMAKE_SOURCE}")
list(REMOVE_DUPLICATES CPP_SOURCES)
foreach(SOURCE IN LISTS CPP_SOURCES)
  string(REPLACE "/" "\\" VS_PATH "${SOURCE}")
  string(FIND "${VS_SOURCE}" "<ClCompile Include=\"..\\${VS_PATH}\"" POSITION)
  if(POSITION EQUAL -1)
    message(FATAL_ERROR "Visual Studio project omits ${SOURCE}")
  endif()
endforeach()
foreach(RESOURCE IN ITEMS "FastFile.rc" "FastFile.manifest")
  string(FIND "${VS_SOURCE}" "${RESOURCE}" POSITION)
  if(POSITION EQUAL -1)
    message(FATAL_ERROR "Visual Studio project omits ${RESOURCE}")
  endif()
endforeach()
message(STATUS "Production C++ sources and application resources are present in both builds")

foreach(BUILD_SOURCE IN ITEMS CMAKE_SOURCE VS_SOURCE)
  string(FIND "${${BUILD_SOURCE}}" "FASTFILE_AGENT_EXECUTABLE" POSITION)
  if(POSITION EQUAL -1)
    message(FATAL_ERROR "${BUILD_SOURCE} omits the independent agent entry point")
  endif()
endforeach()
