if(NOT DEFINED PROJECT_VERSION OR NOT DEFINED VERSION_FILE OR NOT DEFINED INSTALLER_SCRIPT)
  message(FATAL_ERROR "PROJECT_VERSION, VERSION_FILE and INSTALLER_SCRIPT are required")
endif()

file(STRINGS "${VERSION_FILE}" SOURCE_VERSION LIMIT_COUNT 1)
string(STRIP "${SOURCE_VERSION}" SOURCE_VERSION)
if(NOT SOURCE_VERSION STREQUAL PROJECT_VERSION)
  message(FATAL_ERROR "CMake project version ${PROJECT_VERSION} differs from VERSION (${SOURCE_VERSION})")
endif()

file(READ "${INSTALLER_SCRIPT}" INSTALLER_SOURCE)
string(FIND "${INSTALLER_SOURCE}" "Join-Path $root 'VERSION'" VERSION_SOURCE_INDEX)
if(VERSION_SOURCE_INDEX EQUAL -1)
  message(FATAL_ERROR "Installer script must read its default version from the root VERSION file")
endif()

message(STATUS "Version source is consistent: ${SOURCE_VERSION}")
